# Generated by Django 4.1.5 on 2023-01-26 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Urgent', 'Urgent')], default='Low', max_length=10)),
            ],
        ),
    ]
