# Generated by Django 4.1.5 on 2023-01-26 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
