# Generated by Django 4.1.5 on 2023-01-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
